version: '3'

services:
  notifier:
    image: paulosalonso/notifier:0.0.1
    ports:
      - 8080:8080
    environment:
      NOTIFIER_EMAIL_SENDER: Paulo Alonso <paulo_alonso_@hotmail.com>
      NOTIFIER_EMAIL_SANDBOX_RECIPIENTS: paulo_alonso_@hotmail.com
      NOTIFIER_EMAIL_SERVICE_TYPE: fake
      KAFKA_BROKER: kafka:9092
      KAFKA_SCHEMA_REGISTRY: http://schema-registry:8081
    depends_on:
      - schema-registry
    networks:
      - notifier
      
      
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - notifier

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "notifications:1:1"
    networks:
      - notifier
      
  schema-registry:
    image: confluentinc/cp-schema-registry:latest
    depends_on:
      - kafka
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: 'zookeeper:2181'
    networks:
      - notifier
      
networks: 
  notifier:
    driver: bridge
